### PR TITLE
implement feature request for more efficient output

### PR DESCRIPTION
**Pull request by sachseka**
please check

### CODE REVIEW

**Review by schumaki — COMMENTED** [review]
That's a great start!

Maybe consider moving the case-IDs into the brackets.
Momentarily it looks like this:

```
── Check: Valid and missing codes 
ℹ Deviations from design detected!
✖ Found for 4 subunits sysMis instead of valid codes for booklet `TH03`: Var1, Var2, Var3, and Var4
ℹ Var1, Var2, Var4 (15 cases): 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, and 1014
ℹ Var3 (10 cases): 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, and 1014
```

Additionally, with many subunits it becomes hard to spot the beginning of the cases. I would consider a linebreak there, i. e.:
```
── Check: Valid and missing codes 
ℹ Deviations from design detected!
✖ Found for 4 subunits sysMis instead of valid codes for booklet `TH03`: Var1, Var2, Var3, and Var4
ℹ Var1, Var2, Var4 
ℹ (15 cases: 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, and 1014)
ℹ Var3 
ℹ (10 cases: 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, and 1014)
```

**Comment by sachseka** [comment]
Thank you for your suggestion. I understand your perspective, but I believe the current format provides clarity and cohesion by keeping the related information together on one line. For instance:

    ℹ Var1, Var2, Var4 (15 cases): 1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011, 1012, 1013, and 1014

This format ensures that readers can easily identify the variables and their associated cases without having to scan multiple lines. The use of brackets also serves as a clear visual cue for the beginning of the case list.

Could you please clarify how the suggested change would enhance readability or understanding? I'm open to discussing this further if you have additional reasons for the revision.

**Comment by schumaki** [comment]
With many (>10 subunits) and many cases this format becomes a bit hard to spot the beginning of the cases (see PM on zoom for an example). Maybe only implement a linebreak for more than 10 subunits?

**Review by schumaki — APPROVED** [review]
It is definitly an improvement and works as intended.
Further improvements can be left for future discussions.

so... approved.

**Pull request merged**
